
apiVersion: v1
kind: Config

clusters:
- name: k3s-cluster
  cluster:
    server: https://10.0.1.190:32114 # C'est l'adresse du control-plane
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpjMk5qYzJNVGN3SGhjTk1qWXdOVEF4TVRrek16TTNXaGNOTXpZd05ESTRNVGt6TXpNMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpjMk5qYzJNVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSNUdmQlJYSkpwdGhvWElRUWZXdHcrV0F1S1hsdFBXRzU2VmF4TE9vWWUKUFlaaitvaXJ1b1NVNGJFcTR0ODMyZ0t5Y2pPMnhCZ1BoZHc3TE5FTE83bjJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVVIcmoxVU13T0VkYWRlZ1VjVnE0Cko1dHZwdlF3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTjlsN3JaQ0VzZ0luZUFRVlhFMm1ZMGdvaUVSVUJsUkMKWlFmcE5uUDZmVFFDSUVzWk9zdk12VXhHNTdKNmQ5L1lNSlF4dzc5SnRmN29CUk04NUJXSFYzY24KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

users:
- name: etudiant
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkZoVlBCQWVILTNLWVZHekpBcEY5Y1NPZE9sanBkUzVUZjRWbExXNlRReFUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzc3Njc1NjMyLCJpYXQiOjE3Nzc2NzIwMzIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZjkyYTcwMDYtNDZmMy00YjFjLTg5MTUtMzE4MGU3NTJkZWYzIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYiLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiZXR1ZGlhbnQtc3J2YWNjb3VudCIsInVpZCI6IjUxMTc1MGIzLTQzYTItNDJiZi05MjRiLWVjZGY5YzBlMDIxYSJ9fSwibmJmIjoxNzc3NjcyMDMyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGV2OmV0dWRpYW50LXNydmFjY291bnQifQ.iGYdgaVwSQNj5NlLhSaoaFrMFJ0j9u-z_sxTiHHLxBKw6QQJCESd2fDjbl-bOOOI1CfScCNVCmBrydQPJl7lRgG27_lenRzUvan3w9j2jvVhzhYVznwnOwVzpp4go-PVEDsNyjFys8pWV1-zg7kOtMItr6pRSMzeZWp9OHzfZkDFHpD4rdQwXMZsA7zGLUM-ZgGS1YPzcw8UGDNciOpJr6KnL5uj-9WLeIOoKXFNkvjnqZKXqwxtFI72u9_SX942NnQlyUprbby2vjHXO5BLvhimwLvPaVlHkVxP-UUjNd20NdEOIATEqEf0EbaGbdwGFSZMtAoHRC8rIF62CxrxhQ

contexts:
- name: etudiant-context
  context:
    cluster: k3s-cluster
    user: etudiant
    namespace: dev

current-context: etudiant-context
